A= set([1,2,3,4])
B= set([4,5,6,7,8])
print("conjunto A", A)
print("conjunto B", B) 
print("union", A|B)
print("intersección", A&B)
print("Diferencia A-B", A-B)
print("Diferencia B-A", B-A)
print(f"Diferencia simétrica A-B", A^B)
